# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea2cb4c9cb4419b591c3765a2cddcbb3d65fbcd865cfb1543588a6764a6c3f523065b4e73dfd32375cf17cb25fa0e52569f155a06f5581c7eb28efa675cc687e

test:
  secret_key_base: 3f1019ee84810ccc1561559e4702ffd4ae117ff109d71aca51884fe99cce88f3b2da45d6b7c7e852104b0720f5501f581cbaacae0689c82576a8460894e0ce77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
